# -*- coding: utf-8 -*-
"""Air.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1co5MkvgtiOforTFb8GHxkxXTnAJAM6vl
"""

class Air:
    def __init__(self, temp=298.15):
        self.T = temp
    def getViscosity(self):
        return 1.72E-5*393/(self.T+120)*(self.T/273)**1.5